[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
axum = "0.7.9"
chrono = "0.4.39"
dotenvy = "0.15.7"
serde = { version = "1.0.216", features = ["derive"] }
sled = "0.34.7"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }
