name: Build and Deploy Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and push `proxy` Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --cache-from type=registry,ref=ghcr.io/magwoo/leasing-proxy:cache \
            --cache-to type=registry,ref=ghcr.io/magwoo/leasing-proxy:cache,mode=max \
            --tag ghcr.io/magwoo/leasing-proxy:latest \
            --push \
            .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOST_KEY }}

      - name: Copy docker-compose.yml to server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDR }}:leasing

      - name: Pull and Start Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDR }} 'cd leasing && docker compose pull && docker compose up -d'
